{"name": "Авторизация курьером с несуществующими данными", "status": "passed", "description": "Проверяем, что нельзя авторизоваться под несуществующим пользователем, в логине. Приходит ответ 404 с соответствующим письменным уведомлением", "steps": [{"name": "Создание рандомных регистрационных данных", "status": "passed", "start": 1734285265323, "stop": 1734285265323}], "start": 1734285265323, "stop": 1734285265586, "uuid": "48505a71-4c57-45b4-9276-d5c1d5ae6490", "historyId": "66785b1c126aadbdccd73d6a3ddc1fcf", "testCaseId": "66785b1c126aadbdccd73d6a3ddc1fcf", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_without_registration", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WIN-6V4RJG7CMFA"}, {"name": "thread", "value": "18792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}